# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Check for Updates
# on: [pull_request, push]
on:
    pull_request:
    push:
        paths-ignore: 
            - .github/**/*
        tags-ignore:
            - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml