name: Publish to Releases
permissions:
  contents: write

on:
  release:
    types:
      - created

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact_name: published

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: published

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            **/*.jar