name: Publish to Releases

on:
  release:
    types:
      - created

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact_name: published

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: published

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '**/*.jar'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true